//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQvsSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CellPhone
    {
        public int CellPhoneID { get; set; }
        public string Number { get; set; }
        public Nullable<int> CellPhoneColorID { get; set; }
    
        public virtual CellPhoneColor CellPhoneColor { get; set; }
    }
}
